classDiagram
    class Main {
        +x
    }

    class SNIESController {
        +x
    }

    class GestorCSV {
        +x
    }

    class ProgramaAcademico {
        +x
    }

    class Consolidado {
        +x
    }

    class View {
        +x
    }

    Main --> View
    SNIESController --> GestorCSV
    SNIESController --> ProgramaAcademico
    ProgramaAcademico --> Consolidado
    View --> SNIESController
